# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main
- devel
- feature/*
- release/*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'

pool:
  vmImage: $(imageName)

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.x'

- script: 'dotnet tool update -g dotnet-format && dotnet format --check --verbosity diagnostic'
  displayName: 'dotnet lint'

- script: dotnet build /WarnAsError
  displayName: 'dotnet build'

- script: dotnet test --no-build --verbosity normal
  displayName: 'dotnet test'