// <auto-generated />
using System;
using FestivalApp.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FestivalApp.DAL.Migrations
{
    [DbContext(typeof(FestivalDbContext))]
    [Migration("20210601215040_NewInfoInSeeds")]
    partial class NewInfoInSeeds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FestivalApp.DAL.Entities.BandEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("021ba853-d557-49e8-166b-08d91df9dde1"),
                            CountryOfOrigin = "USA",
                            Genre = "Rock",
                            LongDescription = "Nirvana was an American rock band formed in Aberdeen, Washington in 1987. Founded by lead singer and guitarist Kurt Cobain and bassist Krist Novoselic, the band went through a succession of drummers before recruiting Dave Grohl in 1990. Nirvana's success popularized alternative rock, and they were often referenced as the figurehead band of Generation X. Their music maintains a popular following and continues to influence modern rock and roll culture.",
                            Name = "Nirvana",
                            Photo = "https://happymag.tv/wp-content/uploads/2018/01/earlynirvanahappy.jpg",
                            ShortDescription = "Culture Group"
                        },
                        new
                        {
                            Id = new Guid("7073c336-588a-4193-ccb1-08d91dfb2c3a"),
                            CountryOfOrigin = "USA",
                            Genre = "Pop",
                            LongDescription = "Shawn Corey Carter (born December 4, 1969), known professionally as Jay-Z (stylized as JAY-Z),[a] is an American rapper, songwriter, record executive, businessman, and record producer. He is widely regarded as one of the most influential hip-hop artists in history,[5] and often cited as one of the greatest rappers of all time.[6][7]",
                            Name = "Jay-Z",
                            Photo = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fclassicalbumsundays.com%2Fnirvanas-nevermind-a-memory-replay-presented-colleen-cosmo-murphy%2F&psig=AOvVaw3Y8MjLEMygFfHWH1hV0Rhv&ust=1621455736225000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLCcv--U1PACFQAAAAAdAAAAABAD",
                            ShortDescription = "Best-selled rapper"
                        },
                        new
                        {
                            Id = new Guid("09ab0c58-21fd-4245-316f-08d91dfb8a09"),
                            CountryOfOrigin = "USA",
                            Genre = "Pop",
                            LongDescription = "Billie Eilish Pirate Baird O'Connell (/ˈaɪlɪʃ/ EYE-lish;[1] born December 18, 2001) is an American singer and songwriter. She first gained attention in 2015 when she uploaded the song 'Ocean Eyes' to SoundCloud, which was subsequently released by the Interscope Records subsidiary Darkroom. The song was written and produced by her brother Finneas O'Connell, with whom she collaborates on music and live shows. Her debut EP, Don't Smile at Me (2017), became a sleeper hit, reaching the top 15 in the US, UK, Canada, and Australia.",
                            Name = "Billie Eilish",
                            Photo = "https://cdn.myshoptet.com/usr/www.esuvenyry.cz/user/documents/upload/nirvana.jpg",
                            ShortDescription = "Young nice singer"
                        },
                        new
                        {
                            Id = new Guid("0d446d91-2474-492b-0a6a-08d91dfd4a6d"),
                            CountryOfOrigin = "USA",
                            Genre = "Raggy",
                            LongDescription = "Something very serious.",
                            Name = "Lil Grandma",
                            Photo = "https://frontiersinblog.files.wordpress.com/2020/04/frontiers-psychology-free-from-dance-alternative-interaction-grandchildren-grandparents.jpg?w=1024",
                            ShortDescription = "Rely short description"
                        },
                        new
                        {
                            Id = new Guid("807d16e2-a65e-446d-ba7d-2adde9b7db71"),
                            CountryOfOrigin = "CZ",
                            Genre = "Metal",
                            LongDescription = "Something very serious.",
                            Name = "OMFG",
                            Photo = "https://frontiersinblog.files.wordpress.com/2020/04/frontiers-psychology-free-from-dance-alternative-interaction-grandchildren-grandparents.jpg?w=1024",
                            ShortDescription = "Rely short description"
                        });
                });

            modelBuilder.Entity("FestivalApp.DAL.Entities.PerformanceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BandId");

                    b.HasIndex("StageId");

                    b.ToTable("Performances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77a6f205-992e-4bc9-e461-08d91df9dde0"),
                            BandId = new Guid("021ba853-d557-49e8-166b-08d91df9dde1"),
                            From = new DateTime(2021, 2, 1, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StageId = new Guid("8a4fa0b6-2b26-42ce-2ce3-08d91d019f7c"),
                            To = new DateTime(2021, 2, 1, 22, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7e1d51a8-6840-44de-96ab-08d91dfb2c3a"),
                            BandId = new Guid("021ba853-d557-49e8-166b-08d91df9dde1"),
                            From = new DateTime(2021, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StageId = new Guid("b6345eaa-ecec-42de-a3b8-e16a76bb171d"),
                            To = new DateTime(2021, 1, 1, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3c2c1081-97e9-4b32-0d97-08d91dfb8a09"),
                            BandId = new Guid("7073c336-588a-4193-ccb1-08d91dfb2c3a"),
                            From = new DateTime(2021, 3, 1, 12, 59, 0, 0, DateTimeKind.Unspecified),
                            StageId = new Guid("8a4fa0b6-2b26-42ce-2ce3-08d91d019f7c"),
                            To = new DateTime(2021, 3, 1, 14, 21, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e6ec7542-aad4-466e-a44a-1ba8400bc60e"),
                            BandId = new Guid("09ab0c58-21fd-4245-316f-08d91dfb8a09"),
                            From = new DateTime(2021, 3, 10, 12, 59, 0, 0, DateTimeKind.Unspecified),
                            StageId = new Guid("b6345eaa-ecec-42de-a3b8-e16a76bb171d"),
                            To = new DateTime(2021, 3, 10, 14, 21, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FestivalApp.DAL.Entities.StageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a4fa0b6-2b26-42ce-2ce3-08d91d019f7c"),
                            Capacity = 100,
                            Description = "Stage on blue hills with best view",
                            Name = "Blue hills",
                            Photo = "https://img1.10bestmedia.com/Images/Photos/366598/GettyImages-1093700094_55_660x440.jpg"
                        },
                        new
                        {
                            Id = new Guid("b6345eaa-ecec-42de-a3b8-e16a76bb171d"),
                            Capacity = 100,
                            Description = "Letnany in Prague",
                            Name = "Letnany",
                            Photo = "https://www.google.com/url?sa=i&url=http%3A%2F%2Fwww.pilotinfo.cz%2Fz-letist%2Fceska-republika%2Fjak-se-dela-propaganda-proti-letisti-praha-letnany&psig=AOvVaw18otsYEpIRFlN6krPFBg95&ust=1621456840456000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLif9_6Y1PACFQAAAAAdAAAAABAK"
                        },
                        new
                        {
                            Id = new Guid("99b333d5-20b3-418f-0a5e-08d91dfb2c3b"),
                            Capacity = 100,
                            Description = "Stage3",
                            Name = "Stage3",
                            Photo = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fvysilackymilin.cz%2Fdetail-produktu%2Fautoradia%2Freproduktory%2Fjbl%2F15595_reproduktory-jbl-stage3-427%2F&psig=AOvVaw3TH_XTLko-9dPqaErc05z3&ust=1621613902359000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLC6pY3i2PACFQAAAAAdAAAAABAD"
                        });
                });

            modelBuilder.Entity("FestivalApp.DAL.Entities.PerformanceEntity", b =>
                {
                    b.HasOne("FestivalApp.DAL.Entities.BandEntity", "Band")
                        .WithMany("Performances")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FestivalApp.DAL.Entities.StageEntity", "Stage")
                        .WithMany("Performances")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("FestivalApp.DAL.Entities.BandEntity", b =>
                {
                    b.Navigation("Performances");
                });

            modelBuilder.Entity("FestivalApp.DAL.Entities.StageEntity", b =>
                {
                    b.Navigation("Performances");
                });
#pragma warning restore 612, 618
        }
    }
}
